### PR TITLE
added more frameworks

### PR DESCRIPTION
**Pull request by dhruvdabhi101**
## solving issue no : #4 

tell me if there are any changes ? 
PS: Sorry for the whole file change. (ESLint in the VSCode did all tha by himself and I didn't knew how to get back it to normal) 

## Screenshot : 
screenshot

### CODE REVIEW

**Comment by KanishkKhurana** [comment]
This looks amazing! 
@dhruvdabhi101 did you deploy the smart contract once you made changes to it ?

**Comment by dhruvdabhi101** [comment]
> This looks amazing! 
> 
> @dhruvdabhi101 did you deploy the smart contract once you made changes to it ?

Yeah.. I deployed on ganache.

**Comment by KanishkKhurana** [comment]
> > This looks amazing!
> > @dhruvdabhi101 did you deploy the smart contract once you made changes to it ?
> 
> Yeah.. I deployed on ganache.

I think we should deploy it on a testnet like polygon or avalanche and make changes appropriately. right now when i click on the newly added frameworks, the website goes blank!

**Comment by dhruvdabhi101** [comment]
> > > This looks amazing!
> > > @dhruvdabhi101 did you deploy the smart contract once you made changes to it ?
> > 
> > 
> > Yeah.. I deployed on ganache.
> 
> I think we should deploy it on a testnet like polygon or avalanche and make changes appropriately. right now when i click on the newly added frameworks, the website goes blank!

Okay.. I'll try to fix it and let you know if there is any issue.

**Comment by dhruvdabhi101** [comment]
Will it be okay if i deploy it on mumbai network ?

**Comment by dhruvdabhi101** [comment]
hoping my recent commit will not break the app 😅

**Comment by KanishkKhurana** [comment]
Looks good to me ! good job

**Comment by KanishkKhurana** [comment]
Looks good to me ! good job

**Pull request merged**
